# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bond}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Horner"]
  s.date = %q{2010-05-07}
  s.description = %q{Bond is on a mission to improve irb’s autocompletion. Aside from doing everything irb’s can do and fixing its quirks, Bond can autocomplete argument(s) to methods, uniquely completing per module, per method and per argument. Bond brings irb’s completion closer to bash/zsh as it provides a configuration system and a DSL for creating custom completions and completion rules. With this configuration system, users can customize their irb autocompletions and share it with others. Bond is able to offer more than irb’s completion since it uses a Readline C extension to get the full line of input when completing as opposed to irb’s last-word approach.}
  s.email = %q{gabriel.horner@gmail.com}
  s.extensions = ["ext/readline_line_buffer/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "ext/readline_line_buffer/extconf.rb",
     "ext/readline_line_buffer/readline_line_buffer.c",
     "lib/bond.rb",
     "lib/bond/agent.rb",
     "lib/bond/completion.rb",
     "lib/bond/completions/activerecord.rb",
     "lib/bond/completions/array.rb",
     "lib/bond/completions/bond.rb",
     "lib/bond/completions/hash.rb",
     "lib/bond/completions/kernel.rb",
     "lib/bond/completions/module.rb",
     "lib/bond/completions/object.rb",
     "lib/bond/completions/struct.rb",
     "lib/bond/input.rb",
     "lib/bond/m.rb",
     "lib/bond/mission.rb",
     "lib/bond/missions/anywhere_mission.rb",
     "lib/bond/missions/default_mission.rb",
     "lib/bond/missions/method_mission.rb",
     "lib/bond/missions/object_mission.rb",
     "lib/bond/missions/operator_method_mission.rb",
     "lib/bond/rawline.rb",
     "lib/bond/rc.rb",
     "lib/bond/readline.rb",
     "lib/bond/search.rb",
     "lib/bond/version.rb",
     "test/agent_test.rb",
     "test/anywhere_mission_test.rb",
     "test/bacon_extensions.rb",
     "test/bond_test.rb",
     "test/completion_test.rb",
     "test/completions_test.rb",
     "test/method_mission_test.rb",
     "test/mission_test.rb",
     "test/object_mission_test.rb",
     "test/operator_method_mission_test.rb",
     "test/search_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://tagaholic.me/bond/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{tagaholic}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mission: Easy custom autocompletion for arguments, methods and beyond. Accomplished for irb and any other readline-like console environments.}
  s.test_files = [
    "test/agent_test.rb",
     "test/anywhere_mission_test.rb",
     "test/bacon_extensions.rb",
     "test/bond_test.rb",
     "test/completion_test.rb",
     "test/completions_test.rb",
     "test/method_mission_test.rb",
     "test/mission_test.rb",
     "test/object_mission_test.rb",
     "test/operator_method_mission_test.rb",
     "test/search_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

